//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Testcase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPlaylists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tPlaylists()
        {
            this.tPLentries = new HashSet<tPLentries>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Last { get; set; }
        public Nullable<int> Row { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tPLentries> tPLentries { get; set; }
    }
}
