//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Testcase.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPlaylistSongs
    {
        public int ID { get; set; }
        public string Genre { get; set; }
        public string Catalog { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
        public string Titel { get; set; }
        public string Pfad { get; set; }
        public string FileName { get; set; }
        public int PLID { get; set; }
    }
}
